kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: rancher-demo-app
  namespace: fleet-default
spec:
  repo: https://github.com/bgregorius-rgs/rancher-app.git
  branch: army
  targets:
  - name: demo
    clusterSelector:
      matchLabels:
        demo: enabled
  paths:
  - "./helm"
